name: Telegram notifications

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Telegram Notify
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: |
          https://github.com/${{ github.actor }} performed _${{ github.event_name }}_:
          https://github.com/${{ github.repository }}/commit/${{ github.event.after }}.
